class Constants:
    """Class for storing Gothic cheat constants."""

    # Pointers to game memory
    SKILL_POINTS_POINTER = (0x0046A3DC, 0x324)  # Skill points pointer's and value's offsets
    STRENGTH_POINTER = (0x0046A3DC, 0x194)  # Strength pointer's and value's offsets
    AGILITY_POINTER = (0x0046A3DC, 0x198)  # Agility pointer's and value's offsets
    MARVIN_POINTER = (0x004DA6BC, 0xB0)  # Marvin mode pointer's and value's offsets

    # Inputs
    CONSOLE_KEY = "{F2}"
    ENTER_CHEAT_KEY = "{ENTER}"
    B_CHEATS = "B"
    CANCEL_B_CHEATS = "42"

    # NPCs codes (cropped because of command autocomplete)
    NPC_MEAT_BUG = "me"
    NPC_MOLE_RAT = "mol"
    NPC_BABE = "babe"
    NPC_BABE2 = "babe2"
    NPC_BABE3 = "babe3"
    NPC_BABE4 = "babe4"
    NPC_BABE5 = "babe5"
    NPC_BABE6 = "babe6"
    NPC_BABE7 = "babe7"
    NPC_SWAMP_SHARK = "sw"
    NPC_TROLL = "tro"
    NPC_STONE_GOLEM = "stoneg"
    NPC_ICE_GOLEM = "ic"
    NPC_FIRE_GOLEM = "fireg"
    NPC_SLEEPER = "sleep"
    NPC_HARPIE = "ha"
    NPC_SCAVENGER = "scav"
    NPC_SNAPPER = "sna"
    NPC_DEMON = "demon"
    NPC_SHADOW_BEAST = "shad"
    NPC_MINECRAWLER_QUEEN = "minecrawlerq"
    NPC_WARAN = "war"
    NPC_YOUNG_TROLL = "yo"
    NPC_BRIDGE_GOLEM = "br"
    NPC_FIRE_WARAN = "firew"
    NPC_BLOODFLY = "bloodf"
    NPC_BLOODHOUND = "bloodh"
    NPC_RAZOR = "raz"
    NPC_LURKER = "lur"
    NPC_DAMM_LURKER = "dam"
    NPC_YOUNG_SCAVENGER = "ys"
    NPC_YOUNG_MOLERAT = "ym"
    NPC_WOUNDED_SWAMP_SHARK = "hu"
    NPC_MINECRAWLER = "minecrawler"
    NPC_MINECRAWLER_WARRIOR = "minecrawlerw"
    NPC_SHAMAN_ROCKEFELLER = "sham"
    NPC_UNDEAD_SHAMAN_ROCKEFELLER = "ud"
    NPC_FREE_MINE_ORC = "fr"
    NPC_WOLF = "wolf"
    NPC_SKELETON = "skeleton"
    NPC_SKELETON_WARRIOR = "skeletonw"
    NPC_SKELETON_SCOUT = "skeletons"
    NPC_SKELETON_MAGE = "skeletonmage"
    NPC_ORC_DOG = "orcd"
    NPC_ORC_BITER = "orcb"
    NPC_XARDAS_DEMON = "xa"
    NPC_BATH_BABE = "bat"
    NPC_BABE_ROCKEFELLER = "babe_"

    # Waypoint codes
    WP_START_GAME = "start"
    WP_OLD_CAMP_1 = "oc1"
    WP_OLD_CAMP_2 = "oc2"
    WP_GOMEZ = "occ_barons_dance"
    WP_CORRISTO = "occ_chapel_upstairs"
    WP_OLD_MINE = "ow_om_entrance01"
    WP_NEW_CAMP_ENTRANCE = "nc_path50"
    WP_NEW_CAMP = "nc_entrance_wp"
    WP_LEE = "nc_small_cave_center"
    WP_SATURAS = "nc_kdw_cave_entrance"
    WP_FREE_MINE = "fms_entrance"
    WP_ORE_PIT = "nc_pit_center"
    WP_SECT_SWAMP = "psi_start"
    WP_Y_BERION = "psi_temple_rooms"
    WP_COR_KALOM = "psi_labor_in"
    WP_XARDAS_TOWER = "dt_maingate"
    WP_XARDAS = "dt_library"
    WP_CASTLE_RUIN = "castle"
    WP_LIGHTTOWER = "fogtower_out"
    WP_TROLL_VALLEY = "location_12_01"
    WP_OLD_CASTLE = "location_19_03"
    WP_MONASTERY = "location_28_01"
    WP_BLACK_GOBLINS = "location_29_02"
    WP_MAGIC_TOWER = "mt_01"
    WP_ORC_BRIDGE = "ow_orcbridge"
    WP_ORC_GRAVEYARD = "ow_path_198_orcgraveyard7"
    WP_SLEEPER_TEMPLE = "ow_sleeperentrance"
    WP_STONEHENGE = "stones"
    WP_FIRST_FOCUS_STONE = "wp_circle_01"
    WP_CASTLE_TOWER_TOP = "castle_tower_top"
    WP_OCC_TOWER_PLATFORM = "occ_tower_platform"
